import { Dimensions, StyleSheet } from 'react-native';
import { Colors } from './colors';

const { width } = Dimensions.get('window');
const isWide = width > 600;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  introSection: {
    paddingHorizontal: 20,
    marginTop: 24,
    marginBottom: 16,
    zIndex: 1,
  },
  introTitle: {
    fontSize: 27,
    lineHeight: 34,
    fontWeight: '900',
    marginBottom: 8,
    letterSpacing: -0.4,
  },
  introText: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
  },
  searchBox: {
    marginHorizontal: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    height: '100%',
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '600',
  },
  savedToggleWrapper: {
    paddingHorizontal: 20,
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  savedToggle: {
    height: 42,
    paddingHorizontal: 15,
    borderRadius: 21,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  savedToggleText: {
    fontSize: 13,
    fontWeight: '800',
  },
  filterGroup: {
    marginBottom: 12,
  },
  filterGroupTitle: {
    paddingHorizontal: 20,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: -0.1,
  },
  filtersScroll: {
    paddingHorizontal: 20,
    gap: 10,
    paddingBottom: 2,
  },
  filterChip: {
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: '800',
  },
  heroSection: {
    paddingHorizontal: 20,
    marginTop: 8,
    marginBottom: 24,
  },
  featuredCard: {
    height: 238,
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  featuredImage: {
    width: '100%',
    height: '100%',
  },
  featuredOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  featuredBadgesRow: {
    position: 'absolute',
    top: 15,
    left: 15,
    right: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  featuredTopBadge: {
    backgroundColor: Colors.brand.blue,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  featuredHeartButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  featuredBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  featuredBottom: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
  },
  featuredLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  featuredTitle: {
    color: 'white',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
    marginBottom: 4,
    letterSpacing: -0.4,
  },
  featuredSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    lineHeight: 19,
    marginBottom: 12,
    fontWeight: '600',
  },
  featuredMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  priceTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  priceText: {
    color: 'white',
    fontSize: 13,
    fontWeight: '900',
  },
  dateTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.28)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 13,
  },
  dateTagText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  sectionHeading: {
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  sectionSubheading: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  countText: {
    fontSize: 13,
    fontWeight: '800',
  },
  offersList: {
    paddingHorizontal: 20,
    gap: 14,
  },
  offerCard: {
    borderWidth: 1,
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: isWide ? 'row' : 'column',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
  },
  offerImage: {
    width: isWide ? 190 : '100%',
    height: isWide ? 185 : 158,
  },
  offerContent: {
    flex: 1,
    padding: 15,
  },
  offerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 9,
  },
  offerTitleBox: {
    flex: 1,
    paddingRight: 10,
  },
  offerTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 7,
    marginBottom: 8,
  },
  modalTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 7,
    marginBottom: 10,
  },
  sourceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
  },
  aiBadge: {
    backgroundColor: '#7C3AED',
  },
  userBadge: {
    backgroundColor: Colors.brand.green,
  },
  sourceBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  typeBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: '900',
  },
  offerTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    marginBottom: 3,
    letterSpacing: -0.2,
  },
  offerSubtitle: {
    fontSize: 12,
    fontWeight: '700',
  },
  saveButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerDescription: {
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 13,
    fontWeight: '500',
  },
  offerMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  smallMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 13,
  },
  smallMetaText: {
    fontSize: 12,
    fontWeight: '800',
  },
  centerState: {
    paddingVertical: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerStateText: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyState: {
    marginHorizontal: 20,
    borderWidth: 1,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginTop: 10,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    fontWeight: '500',
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: Colors.brand.blue,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.58)',
  },
  modalCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
    maxHeight: '91%',
  },
  modalHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.72)',
    alignSelf: 'center',
    position: 'absolute',
    top: 10,
    zIndex: 3,
  },
  modalImage: {
    width: '100%',
    height: 218,
  },
  modalCloseButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.48)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    padding: 20,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '900',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  modalAuthor: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  modalStatsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  modalStat: {
    flex: 1,
    borderRadius: 19,
    padding: 14,
    minHeight: 92,
  },
  modalStatValue: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 8,
    marginBottom: 3,
  },
  modalStatLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  modalDescription: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    marginBottom: 18,
    fontWeight: '500',
  },
  createTripButton: {
    height: 54,
    borderRadius: 19,
    backgroundColor: Colors.brand.blue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  createTripButtonDisabled: {
    opacity: 0.7,
  },
  createTripButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
});
