import { Dimensions, StyleSheet } from 'react-native';
import { Colors } from './colors';

const { width } = Dimensions.get('window');
const isWide = width > 600;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  introSection: {
    paddingHorizontal: 20,
    marginTop: 22,
    marginBottom: 14,
  },
  introTitle: {
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '900',
    marginBottom: 8,
    letterSpacing: -0.35,
  },
  introText: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
  },
  searchBox: {
    marginHorizontal: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 14,
    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    height: '100%',
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '600',
  },
  filterToolbar: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 12,
    gap: 10,
  },
  filterButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterButtonIconBox: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.brand.blue,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 11,
  },
  filterButtonTextBox: {
    flex: 1,
    paddingRight: 8,
  },
  filterButtonTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  filterButtonSubtitle: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
    marginTop: 2,
  },
  filterCounter: {
    minWidth: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: Colors.brand.blue,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 7,
  },
  filterCounterText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  favoriteQuickButton: {
    width: 58,
    minHeight: 58,
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeFiltersWrap: {
    marginBottom: 12,
  },
  activeFiltersScroll: {
    paddingHorizontal: 20,
    gap: 8,
  },
  activeFilterChip: {
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activeFilterText: {
    fontSize: 12,
    fontWeight: '800',
  },
  clearInlineButton: {
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,77,103,0.14)',
  },
  clearInlineButtonText: {
    color: '#FF4D67',
    fontSize: 12,
    fontWeight: '900',
  },
  heroSection: {
    paddingHorizontal: 20,
    marginTop: 4,
    marginBottom: 22,
  },
  featuredCard: {
    height: 236,
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  featuredImage: {
    width: '100%',
    height: '100%',
  },
  featuredOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  featuredBadgesRow: {
    position: 'absolute',
    top: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  featuredTopBadge: {
    backgroundColor: Colors.brand.blue,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: '68%',
  },
  featuredHeartButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  featuredBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  featuredBottom: {
    position: 'absolute',
    bottom: 18,
    left: 18,
    right: 18,
  },
  featuredLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  featuredTitle: {
    color: 'white',
    fontSize: 27,
    lineHeight: 32,
    fontWeight: '900',
    marginBottom: 5,
    letterSpacing: -0.4,
  },
  featuredSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    lineHeight: 19,
    marginBottom: 12,
    fontWeight: '600',
  },
  featuredMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  priceTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  priceText: {
    color: 'white',
    fontSize: 13,
    fontWeight: '900',
  },
  dateTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.32)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 13,
  },
  dateTagText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    marginBottom: 13,
    gap: 12,
  },
  sectionTitleBox: {
    flex: 1,
  },
  sectionHeading: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  sectionSubheading: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    marginTop: 2,
  },
  countText: {
    fontSize: 13,
    fontWeight: '900',
    flexShrink: 0,
  },
  offersList: {
    paddingHorizontal: 20,
    gap: 14,
  },
  offerCard: {
    borderWidth: 1,
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: isWide ? 'row' : 'column',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
  },
  offerImage: {
    width: isWide ? 190 : '100%',
    height: isWide ? 185 : 150,
  },
  offerContent: {
    flex: 1,
    padding: 15,
  },
  offerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 9,
  },
  offerTitleBox: {
    flex: 1,
    paddingRight: 10,
  },
  offerTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 7,
    marginBottom: 8,
  },
  modalTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 7,
    marginBottom: 10,
  },
  sourceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
  },
  aiBadge: {
    backgroundColor: '#7C3AED',
  },
  userBadge: {
    backgroundColor: Colors.brand.green,
  },
  sourceBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  typeBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: '900',
  },
  offerTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    marginBottom: 3,
    letterSpacing: -0.2,
  },
  offerSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  saveButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerDescription: {
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 13,
    fontWeight: '500',
  },
  offerMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  smallMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 13,
    maxWidth: '100%',
  },
  smallMetaText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  centerState: {
    paddingVertical: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerStateText: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyState: {
    marginHorizontal: 20,
    borderWidth: 1,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginTop: 10,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    fontWeight: '500',
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: Colors.brand.blue,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.58)',
  },
  filterSheet: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: '90%',
    paddingTop: 20,
    overflow: 'hidden',
  },
  filterSheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 18,
    gap: 14,
  },
  filterSheetTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    letterSpacing: -0.25,
  },
  filterSheetSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    marginTop: 3,
  },
  sheetCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  filterSheetContent: {
    paddingHorizontal: 20,
    paddingBottom: 108,
  },
  sheetGroup: {
    marginBottom: 24,
  },
  sheetGroupTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
    marginBottom: 12,
  },
  sheetGroupSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
    marginBottom: 10,
  },
  sheetOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 9,
    rowGap: 10,
  },
  sheetOption: {
    minHeight: 40,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  sheetOptionText: {
    fontSize: 13,
    fontWeight: '800',
  },
  sheetFavoriteRow: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
    marginBottom: 8,
  },
  sheetFavoriteTextBox: {
    flex: 1,
    paddingRight: 12,
  },
  sheetFavoriteTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
    marginBottom: 2,
  },
  sheetFavoriteSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  filterSheetActions: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.18)',
  },
  secondarySheetButton: {
    height: 50,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondarySheetButtonText: {
    fontSize: 14,
    fontWeight: '900',
  },
  primarySheetButton: {
    height: 50,
    borderRadius: 18,
    backgroundColor: Colors.brand.blue,
    flex: 1.25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primarySheetButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  modalCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
    maxHeight: '91%',
  },
  modalHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.72)',
    alignSelf: 'center',
    position: 'absolute',
    top: 10,
    zIndex: 3,
  },
  modalImage: {
    width: '100%',
    height: 214,
  },
  modalCloseButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.48)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    padding: 20,
    paddingBottom: 26,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '900',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  modalAuthor: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  modalStatsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  modalStat: {
    flex: 1,
    borderRadius: 19,
    padding: 14,
    minHeight: 92,
  },
  modalStatValue: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 8,
    marginBottom: 3,
  },
  modalStatLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  modalDescription: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    marginBottom: 18,
    fontWeight: '500',
  },
  createTripButton: {
    minHeight: 54,
    borderRadius: 19,
    backgroundColor: Colors.brand.blue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  createTripButtonDisabled: {
    opacity: 0.7,
  },
  createTripButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
});
