import { StyleSheet } from 'react-native';
import { Colors } from './colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    marginTop: 30,
    zIndex: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 18,
  },
  sectionTitleBox: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 26,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  sectionSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    marginTop: 8,
  },
  createSmallButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.brand.blue,
    marginTop: 4,
  },
  tripCard: {
    borderRadius: 26,
    marginBottom: 18,
    overflow: 'hidden',
    borderWidth: 1,
  },
  tripImage: {
    width: '100%',
    height: 176,
  },
  imageOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 176,
  },
  tripImageContent: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 16,
    height: 142,
    justifyContent: 'space-between',
  },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  destination: {
    color: '#FFFFFF',
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  tripDates: {
    color: 'rgba(255,255,255,0.84)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    marginTop: 3,
  },
  tripInfo: {
    padding: 16,
  },
  tripMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  metaPillText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
  },
  tripFooter: {
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.16)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  tripRoleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  tripRoleText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
  },
  manageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.brand.blue,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  manageButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
  },
  overviewGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  overviewCard: {
    flex: 1,
    minHeight: 84,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    justifyContent: 'space-between',
  },
  overviewValue: {
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '900',
    marginTop: 8,
  },
  overviewLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  tripTabs: {
    marginHorizontal: -20,
    marginBottom: 16,
  },
  tripTabsContent: {
    paddingHorizontal: 20,
    gap: 9,
  },
  tripTab: {
    height: 42,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  tripTabText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
  },
  cardBadgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  accessBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  accessBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  tripImageTextBox: {
    gap: 3,
  },
  stateBox: {
    minHeight: 260,
    borderRadius: 26,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 12,
  },
  stateTitle: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
    textAlign: 'center',
  },
  stateText: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 8,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 11,
    backgroundColor: Colors.brand.blue,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  emptyCard: {
    minHeight: 300,
    borderRadius: 28,
    borderWidth: 1,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.brand.blue,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 8,
  },
  emptyButton: {
    marginTop: 18,
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 13,
    backgroundColor: Colors.brand.blue,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  modalTitleBox: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  modalSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    marginTop: 3,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  panelHero: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: 16,
  },
  panelHeroGradient: {
    padding: 18,
    minHeight: 112,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  panelHeroText: {
    flex: 1,
  },
  panelHeroTitle: {
    color: '#FFFFFF',
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
  },
  panelHeroSubtitle: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  readOnlyNotice: {
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 22,
  },
  readOnlyText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  modalSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 2,
  },
  modalSectionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
  },
  modalSectionCount: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  peopleCard: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: 22,
  },
  personRow: {
    minHeight: 72,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  personInfo: {
    flex: 1,
    minWidth: 0,
  },
  personNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  personName: {
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
  },
  personSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  personCost: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 4,
  },
  ownerBadge: {
    color: '#FFFFFF',
    backgroundColor: Colors.brand.green,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    overflow: 'hidden',
  },
  avatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  smallActionButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButton: {
    backgroundColor: 'rgba(239,68,68,0.12)',
  },
  addParticipantButton: {
    minWidth: 74,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.brand.blue,
    paddingHorizontal: 14,
  },
  addParticipantText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  inlineLoader: {
    minHeight: 92,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyFriendsBox: {
    minHeight: 108,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    gap: 9,
  },
  emptyInlineText: {
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },

  tripDetailsHero: {
    borderRadius: 28,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: 16,
  },
  tripDetailsImage: {
    width: '100%',
    height: 210,
  },
  tripDetailsOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 210,
  },
  tripDetailsContent: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 16,
    bottom: 18,
    justifyContent: 'space-between',
  },
  tripDetailsTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  tripDetailsSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    marginTop: 5,
  },
  modalTabs: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 22,
    padding: 5,
    gap: 5,
    marginBottom: 18,
  },
  modalTabButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  modalTabButtonActive: {
    backgroundColor: Colors.brand.blue,
  },
  modalTabText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
  },
  detailsGrid: {
    gap: 10,
    marginBottom: 16,
  },
  detailsGridRow: {
    flexDirection: 'row',
    gap: 10,
  },
  detailsCard: {
    flex: 1,
    minHeight: 104,
    borderRadius: 22,
    borderWidth: 1,
    padding: 14,
    justifyContent: 'space-between',
  },
  detailsValue: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 10,
  },
  detailsLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 4,
  },
  descriptionCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 16,
    marginBottom: 16,
  },
  descriptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  descriptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  descriptionTitleBox: {
    flex: 1,
    minWidth: 0,
  },
  descriptionTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '900',
  },
  descriptionSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 1,
  },
  descriptionText: {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
  },
  secondaryButton: {
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.brand.blue,
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
  },
  inlineLoaderSmall: {
    minHeight: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewAvatarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 46,
  },
  previewAvatarWrap: {
    borderWidth: 2,
    borderRadius: 22,
  },
  moreParticipantsBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -10,
  },
  moreParticipantsText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
  },
  previewParticipantsText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginLeft: 12,
  },
});
